export const POLICY_CODES: Record<string, string> = {
	"Resolve merge conflicts": "C1",
	"Minimum number of reviewers": "C2",
	"Required reviewers": "C3",
	ComponentGovernance: "C4",
	"FCIB Governance": "C5",
	LicenseCheck: "C6",
	"pr-block-policy": "C7",
	"review-checker": "C8",
	"Comment requirements": "C9",
	"Git repository settings": "C10",
	"Proof Of Presence": "C11",
	"Require a merge strategy": "C12",
	"Secrets scanning restriction": "C13",
	"whiteboard-app-pr": "W1",
	Build: "W2",
	"docs build verification": "W3",
	"Code Review Compliance Policy": "W4",
	Nitpicker: "W5",
	"Reserved names restriction": "W6",
	"Work item linking": "W7",
	"MerlinBot-FileAffordance/FCIB Governance": "W8",
	"MerlinBot-Nitpicker/Nitpicker": "W9",
	"microsoft-policy-service-CodeReviewCompliancePolicy/Code Review Compliance Policy":
		"W10",
	"whiteboard-app docs verification/codecoverage": "W11",
	"whiteboard-app-pr/codecoverage": "W12",
	"(Preview) Model onboarding validation": "V1",
	"online-meeting-test-probe-e2e": "V2",
	"online-meetings-e2e-pr-gate": "V3",
	"online-meetings-e2e-pr-gate-smart": "V4",
	"Approver Count Policy Validation": "V5",
	"breeze/pr-block-policy": "V6",
	"cg/ComponentGovernance": "V7",
	"merlinbot-productcatalog-inventory/merlinbot-inventory-mapping-status": "V8",
	"merlinbot-pullrequest/merlinbot-LiveSecretsDetection-status": "V9",
	"online-meeting-test-probe-e2e/codecoverage": "V10",
	"online-meetings-adapted-lm-provider-pr/codecoverage": "V11",
	"online-meetings-e2e-pr-gate-smart/codecoverage": "V12",
	"online-meetings-e2e-pr-gate/codecoverage": "V13",
	"Ownership Enforcer": "V14",
};
