-- 0001_initial.sql
-- Core schema for signoff.now (single-instance D1).
-- Apply: wrangler d1 migrations apply signoff-db --remote
--        wrangler d1 migrations apply signoff-db --local
--
-- Design notes:
-- - TEXT UUIDs as primary keys (generated by app/pipeline)
-- - Timestamps are unix epoch **seconds** (UTC)
-- - day_key is TEXT 'YYYY-MM-DD' in instance timezone (Settings.timezone)
-- - Provider-neutral columns; phase-1 rows use provider='ado'
-- - Work Item activities are project-scoped (repo_id NULL); PR activities set repo_id

-- ---------------------------------------------------------------------------
-- Settings (key-value JSON)
-- ---------------------------------------------------------------------------
CREATE TABLE settings (
	key TEXT PRIMARY KEY NOT NULL,
	value TEXT NOT NULL,
	updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- Seed defaults (JSON values as text)
INSERT INTO settings (key, value, updated_at) VALUES
	('timezone', '"Asia/Shanghai"', unixepoch()),
	('email_suffixes', '["example.com"]', unixepoch()),
	(
		'activity_weights',
		'{"pr.merged":10,"pr.closed":2,"pr.created":2,"pr.vote":3,"pr.active":2,"wi.created":3,"wi.updated":1,"wi.closed":5}',
		unixepoch()
	);

-- ---------------------------------------------------------------------------
-- Developers
-- ---------------------------------------------------------------------------
CREATE TABLE developers (
	id TEXT PRIMARY KEY NOT NULL,
	name TEXT NOT NULL,
	-- Stored lowercase for case-insensitive uniqueness / matching
	alias TEXT NOT NULL COLLATE NOCASE,
	created_at INTEGER NOT NULL DEFAULT (unixepoch()),
	updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE UNIQUE INDEX idx_developers_alias ON developers (alias);

-- ---------------------------------------------------------------------------
-- Teams & Tags
-- ---------------------------------------------------------------------------
CREATE TABLE teams (
	id TEXT PRIMARY KEY NOT NULL,
	name TEXT NOT NULL COLLATE NOCASE,
	created_at INTEGER NOT NULL DEFAULT (unixepoch()),
	updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE UNIQUE INDEX idx_teams_name ON teams (name);

CREATE TABLE tags (
	id TEXT PRIMARY KEY NOT NULL,
	name TEXT NOT NULL COLLATE NOCASE,
	-- CSS hex color, e.g. #3B82F6
	color TEXT NOT NULL,
	created_at INTEGER NOT NULL DEFAULT (unixepoch()),
	updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE UNIQUE INDEX idx_tags_name ON tags (name);

CREATE TABLE developer_teams (
	developer_id TEXT NOT NULL,
	team_id TEXT NOT NULL,
	created_at INTEGER NOT NULL DEFAULT (unixepoch()),
	PRIMARY KEY (developer_id, team_id),
	FOREIGN KEY (developer_id) REFERENCES developers (id) ON DELETE CASCADE,
	FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE
);

CREATE TABLE developer_tags (
	developer_id TEXT NOT NULL,
	tag_id TEXT NOT NULL,
	created_at INTEGER NOT NULL DEFAULT (unixepoch()),
	PRIMARY KEY (developer_id, tag_id),
	FOREIGN KEY (developer_id) REFERENCES developers (id) ON DELETE CASCADE,
	FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- Repos (single git repository binding)
-- ---------------------------------------------------------------------------
CREATE TABLE repos (
	id TEXT PRIMARY KEY NOT NULL,
	-- 'ado' | 'github' (phase-1 only writes 'ado')
	provider TEXT NOT NULL DEFAULT 'ado' CHECK (provider IN ('ado', 'github')),
	-- ADO organization name (or GH owner later)
	org TEXT NOT NULL,
	-- ADO project name; for github may mirror owner or be unused
	project TEXT NOT NULL,
	-- Repository name
	name TEXT NOT NULL,
	remote_url TEXT,
	-- Provider external id when known (ADO repository GUID)
	external_id TEXT,
	enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
	created_at INTEGER NOT NULL DEFAULT (unixepoch()),
	updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE UNIQUE INDEX idx_repos_provider_coord ON repos (provider, org, project, name);
CREATE INDEX idx_repos_enabled ON repos (enabled);

-- ---------------------------------------------------------------------------
-- Activities (pipeline write-only; web read-only)
-- ---------------------------------------------------------------------------
CREATE TABLE activities (
	id TEXT PRIMARY KEY NOT NULL,
	developer_id TEXT NOT NULL,
	-- Activity type: pr.merged | pr.closed | pr.created | pr.vote | pr.active
	--               | wi.created | wi.updated | wi.closed | (future extensible)
	type TEXT NOT NULL,
	-- Event instant (UTC unix seconds) from stable provider field
	occurred_at INTEGER NOT NULL,
	-- Natural day in instance timezone: YYYY-MM-DD
	day_key TEXT NOT NULL,
	provider TEXT NOT NULL DEFAULT 'ado' CHECK (provider IN ('ado', 'github')),
	org TEXT NOT NULL,
	project TEXT NOT NULL,
	-- NULL for project-scoped work items; set for PR-related events
	repo_id TEXT,
	-- Stable external key for idempotent upsert / rebuild
	-- Examples:
	--   ado:pr:{org}/{project}/{repo}/{prId}:created
	--   ado:pr:{org}/{project}/{repo}/{prId}:vote:{voter}:{threadId}
	--   ado:wi:{org}/{project}/{wiId}:created
	--   ado:wi:{org}/{project}/{wiId}:updated:{day_key}
	external_ref TEXT NOT NULL,
	-- Source uniqueName that matched (email string); optional audit
	matched_unique_name TEXT,
	-- Optional opaque JSON for display (title snippet, pr number, etc.)
	meta_json TEXT,
	ingested_at INTEGER NOT NULL DEFAULT (unixepoch()),
	FOREIGN KEY (developer_id) REFERENCES developers (id) ON DELETE CASCADE,
	FOREIGN KEY (repo_id) REFERENCES repos (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX idx_activities_external_ref ON activities (external_ref);
CREATE INDEX idx_activities_developer_day ON activities (developer_id, day_key);
CREATE INDEX idx_activities_day ON activities (day_key);
CREATE INDEX idx_activities_type ON activities (type);
CREATE INDEX idx_activities_org_project ON activities (org, project);

-- ---------------------------------------------------------------------------
-- Scores (materialized daily totals; pipeline write-only)
-- ---------------------------------------------------------------------------
CREATE TABLE scores (
	developer_id TEXT NOT NULL,
	day_key TEXT NOT NULL,
	total INTEGER NOT NULL DEFAULT 0,
	-- JSON object: { "pr.merged": 10, "wi.updated": 1, ... }
	breakdown_json TEXT NOT NULL DEFAULT '{}',
	activity_count INTEGER NOT NULL DEFAULT 0,
	computed_at INTEGER NOT NULL DEFAULT (unixepoch()),
	PRIMARY KEY (developer_id, day_key),
	FOREIGN KEY (developer_id) REFERENCES developers (id) ON DELETE CASCADE
);

CREATE INDEX idx_scores_day ON scores (day_key);

-- ---------------------------------------------------------------------------
-- Optional: unmatched identities observed during ingest (web management aid)
-- ---------------------------------------------------------------------------
CREATE TABLE unmatched_identities (
	-- Lowercased uniqueName
	unique_name TEXT PRIMARY KEY NOT NULL,
	provider TEXT NOT NULL DEFAULT 'ado',
	last_seen_at INTEGER NOT NULL DEFAULT (unixepoch()),
	seen_count INTEGER NOT NULL DEFAULT 1,
	sample_org TEXT,
	sample_project TEXT,
	sample_context TEXT
);

-- ---------------------------------------------------------------------------
-- Ingest runs (audit / ops)
-- ---------------------------------------------------------------------------
CREATE TABLE ingest_runs (
	id TEXT PRIMARY KEY NOT NULL,
	started_at INTEGER NOT NULL,
	finished_at INTEGER,
	status TEXT NOT NULL DEFAULT 'running' CHECK (
		status IN ('running', 'success', 'failed', 'partial')
	),
	-- JSON: counts, errors, time window, git sha of pipeline, etc.
	stats_json TEXT,
	error_message TEXT
);

CREATE INDEX idx_ingest_runs_started ON ingest_runs (started_at);
